### ISSUE TITLE
Unable to support Laravel 10

### ISSUE THREAD

**Issue by rubbish-cat** [coding-socks/laravel-upload-handler#79]

**Comment by nerg4l** [comment]
As far as I can tell the package supports Laravel 10.

Do you see any errors? Can you share it?

**Comment by weimi89** [comment]
![Uploading 截圖 2024-01-23 下午2.54.48.png…]()

**Comment by weimi89** [comment]
./composer.json has been updated
Running composer update coding-socks/laravel-upload-handler
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - coding-socks/laravel-upload-handler v0.1.0 requires php ^7.1 -> your php version (8.2.15) does not satisfy that requirement.
    - coding-socks/laravel-upload-handler[v0.2.0, ..., v0.2.1] require php ^7.3 -> your php version (8.2.15) does not satisfy that requirement.
    - coding-socks/laravel-upload-handler v0.2.2 requires illuminate/support ^6.10 || ^7.0 || ^8.0 -> found illuminate/support[v6.10.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - coding-socks/laravel-upload-handler v0.2.3 requires illuminate/support ^6.10 || ^8.0 || ^9.0 -> found illuminate/support[v6.10.0, ..., v6.20.44, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires coding-socks/laravel-upload-handler * -> satisfiable by coding-socks/laravel-upload-handler[v0.1.0, ..., v0.2.3].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require coding-socks/laravel-upload-handler:*" to figure out if any version is installable, or "composer require coding-socks/laravel-upload-handler:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by nerg4l** [comment]
Sorry, my bad. I added support but forgot to release a new version. I just did that.

Please try again and let me know if you run into any issues.

**Comment by weimi89** [comment]
Thank you
